name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v4
      with:
        php-version: '8.4'
        extensions: mbstring, xml

    - name: Install composer dependencies
      run: composer install --no-interaction --no-progress --prefer-dist

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse -c phpstan.neon -l 9 --no-progress

    - name: Run PHPUnit
      run: ./vendor/bin/phpunit --colors=always --testdox
